---
# tasks file for ansible-role-hostname

- include_vars: "{{ ansible_os_family }}.yml"

- name: Fail when hostname_fqdn is not defined
  fail:
    msg: hostname_fqdn must not be empty
  when:
    - not hostname_fqdn is defined

- name: Fail when hostname_fqdn is empty
  fail:
    msg: hostname_fqdn must not be empty
  when:
    - hostname_fqdn | length < 1
    
# XXX replace `include` with `include_task` after all platforms have recent
# version of ansible
- include: "configure-{{ ansible_os_family }}.yml"

- name: Set hostname by hostname(1)
  command: "hostname {% if ansible_os_family == 'Debian' %}{{ hostname_fqdn.split('.') | first }}{% else %}{{ hostname_fqdn }}{% endif %}"
  when:
    - ansible_fqdn != hostname_fqdn

- name: Load facts again
  setup:
  when:
    - ansible_fqdn != hostname_fqdn

- name: Fail if ansible_fqdn has not been updated
  fail:
    msg: "ansible_fqdn (`{{ ansible_fqdn }}`) is not identical with `{{ hostname_fqdn }}`"
  when:
    - ansible_fqdn != hostname_fqdn
